# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import plan

class Ui_Ordo(object):
    def setupUi(self, Ordo):
        Ordo.setObjectName("Ordo")
        Ordo.resize(662, 472)
        Ordo.setStyleSheet("background-color: rgb(192, 236, 242);\n"
"background-color: rgb(249, 252, 255);")
        self.centralwidget = QtWidgets.QWidget(Ordo)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(-40, -60, 721, 541))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("19366.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.sched = QtWidgets.QPushButton(self.centralwidget)
        self.sched.setGeometry(QtCore.QRect(210, 370, 251, 41))
        self.sched.setStyleSheet("background-color: rgb(249, 252, 255);\n"
"border-color: rgb(192, 236, 242);\n"
"font: 12pt \"Gayathri\";")
        self.sched.setObjectName("sched")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 50, 531, 51))
        self.label.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"font: 20pt \"Gayathri\";")
        self.label.setObjectName("label")
        self.label_mach = QtWidgets.QLabel(self.centralwidget)
        self.label_mach.setGeometry(QtCore.QRect(60, 170, 81, 17))
        self.label_mach.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"font: 13pt \"Gayathri\";")
        self.label_mach.setObjectName("label_mach")
        self.label_con = QtWidgets.QLabel(self.centralwidget)
        self.label_con.setGeometry(QtCore.QRect(230, 170, 211, 20))
        self.label_con.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"font: 13pt \"Gayathri\";")
        self.label_con.setObjectName("label_con")
        self.label_prod = QtWidgets.QLabel(self.centralwidget)
        self.label_prod.setGeometry(QtCore.QRect(530, 166, 67, 21))
        self.label_prod.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"font: 13pt \"Gayathri\";")
        self.label_prod.setObjectName("label_prod")
        self.mach_fab = QtWidgets.QSpinBox(self.centralwidget)
        self.mach_fab.setGeometry(QtCore.QRect(60, 125, 71, 31))
        self.mach_fab.setStyleSheet("font: 12pt \"Gayathri\";")
        self.mach_fab.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.mach_fab.setProperty("value", 3)
        self.mach_fab.setObjectName("mach_fab")
        self.mach_fab_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.mach_fab_2.setGeometry(QtCore.QRect(290, 130, 71, 31))
        self.mach_fab_2.setStyleSheet("font: 12pt \"Gayathri\";")
        self.mach_fab_2.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.mach_fab_2.setProperty("value", 2)
        self.mach_fab_2.setObjectName("mach_fab_2")
        self.mach_fab_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.mach_fab_3.setGeometry(QtCore.QRect(530, 130, 71, 31))
        self.mach_fab_3.setStyleSheet("font: 12pt \"Gayathri\";")
        self.mach_fab_3.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.mach_fab_3.setProperty("value", 6)
        self.mach_fab_3.setObjectName("mach_fab_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 300, 181, 31))
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("font: 13pt \"Gayathri\";")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(12)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(410, 300, 181, 31))
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("font: 13pt \"Gayathri\";")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setMaxVisibleItems(12)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_mach_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_mach_2.setGeometry(QtCore.QRect(40, 310, 81, 17))
        self.label_mach_2.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"font: 13pt \"Gayathri\";")
        self.label_mach_2.setObjectName("label_mach_2")
        self.label_mach_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_mach_3.setGeometry(QtCore.QRect(380, 310, 81, 17))
        self.label_mach_3.setStyleSheet("background-color: rgba(191, 64, 64, 0);\n"
"font: 13pt \"Gayathri\";")
        self.label_mach_3.setObjectName("label_mach_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 230, 501, 31))
        self.lineEdit.setStyleSheet("font: 13pt \"Gayathri\";")
        self.lineEdit.setObjectName("lineEdit")
        Ordo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Ordo)
        self.statusbar.setObjectName("statusbar")
        Ordo.setStatusBar(self.statusbar)

        self.retranslateUi(Ordo)
        self.comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Ordo)

    def clic(self):
        plan()

    def retranslateUi(self, Ordo):
        _translate = QtCore.QCoreApplication.translate
        Ordo.setWindowTitle(_translate("Ordo", "Ordonnancement"))
        self.sched.setText(_translate("Ordo", "Obtenir le plan de production"))
        self.label.setText(_translate("Ordo", "Ordonnancement des ateliers de production"))
        self.label_mach.setText(_translate("Ordo", "Machines"))
        self.label_con.setText(_translate("Ordo", "Lignes de conditionnement"))
        self.label_prod.setText(_translate("Ordo", "Produits"))
        self.comboBox.setCurrentText(_translate("Ordo", "Janvier"))
        self.comboBox.setItemText(0, _translate("Ordo", "Janvier"))
        self.comboBox.setItemText(1, _translate("Ordo", "Février"))
        self.comboBox.setItemText(2, _translate("Ordo", "Mars"))
        self.comboBox.setItemText(3, _translate("Ordo", "Avril"))
        self.comboBox.setItemText(4, _translate("Ordo", "Mai"))
        self.comboBox.setItemText(5, _translate("Ordo", "Juin"))
        self.comboBox.setItemText(6, _translate("Ordo", "Juillet"))
        self.comboBox.setItemText(7, _translate("Ordo", "Août  "))
        self.comboBox.setItemText(8, _translate("Ordo", "Septembre"))
        self.comboBox.setItemText(9, _translate("Ordo", "Octobre"))
        self.comboBox.setItemText(10, _translate("Ordo", "Novembre"))
        self.comboBox.setItemText(11, _translate("Ordo", "Décembre"))
        self.comboBox_2.setCurrentText(_translate("Ordo", "Janvier"))
        self.comboBox_2.setItemText(0, _translate("Ordo", "Janvier"))
        self.comboBox_2.setItemText(1, _translate("Ordo", "Février"))
        self.comboBox_2.setItemText(2, _translate("Ordo", "Mars"))
        self.comboBox_2.setItemText(3, _translate("Ordo", "Avril"))
        self.comboBox_2.setItemText(4, _translate("Ordo", "Mai"))
        self.comboBox_2.setItemText(5, _translate("Ordo", "Juin"))
        self.comboBox_2.setItemText(6, _translate("Ordo", "Juillet"))
        self.comboBox_2.setItemText(7, _translate("Ordo", "Août  "))
        self.comboBox_2.setItemText(8, _translate("Ordo", "Septembre"))
        self.comboBox_2.setItemText(9, _translate("Ordo", "Octobre"))
        self.comboBox_2.setItemText(10, _translate("Ordo", "Novembre"))
        self.comboBox_2.setItemText(11, _translate("Ordo", "Décembre"))
        self.label_mach_2.setText(_translate("Ordo", "De"))
        self.label_mach_3.setText(_translate("Ordo", "à"))
        self.lineEdit.setPlaceholderText(_translate("Ordo", "Entrer le nom du fichier contenant les données"))

    def get_ij(self):
        if self.comboBox == "Janvier": 
                return 0






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ordo = QtWidgets.QMainWindow()
    ui = Ui_Ordo()
    ui.setupUi(Ordo)
    Ordo.show()
    sys.exit(app.exec_())
