# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 368)
        MainWindow.setStyleSheet("background-color: rgb(192, 236, 242);\n"
"background-color: rgb(249, 252, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 290, 211, 31))
        self.pushButton.setObjectName("pushButton")
        self.Titre = QtWidgets.QLabel(self.centralwidget)
        self.Titre.setGeometry(QtCore.QRect(210, 70, 301, 31))
        self.Titre.setStyleSheet("")
        self.Titre.setObjectName("Titre")
        self.label_machine = QtWidgets.QLabel(self.centralwidget)
        self.label_machine.setGeometry(QtCore.QRect(20, 140, 331, 21))
        self.label_machine.setObjectName("label_machine")
        self.label_lignes = QtWidgets.QLabel(self.centralwidget)
        self.label_lignes.setGeometry(QtCore.QRect(20, 170, 331, 21))
        self.label_lignes.setObjectName("label_lignes")
        self.label_produit = QtWidgets.QLabel(self.centralwidget)
        self.label_produit.setGeometry(QtCore.QRect(20, 200, 331, 21))
        self.label_produit.setObjectName("label_produit")
        self.mfab = QtWidgets.QSpinBox(self.centralwidget)
        self.mfab.setGeometry(QtCore.QRect(460, 140, 48, 26))
        self.mfab.setObjectName("mfab")
        self.lin = QtWidgets.QSpinBox(self.centralwidget)
        self.lin.setGeometry(QtCore.QRect(460, 170, 48, 26))
        self.lin.setObjectName("lin")
        self.n = QtWidgets.QSpinBox(self.centralwidget)
        self.n.setGeometry(QtCore.QRect(460, 200, 48, 26))
        self.n.setObjectName("n")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ordonnancement"))
        self.pushButton.setText(_translate("MainWindow", "Valider"))
        self.Titre.setText(_translate("MainWindow", "Ordonnancement des atelier de production"))
        self.label_machine.setText(_translate("MainWindow", "Entrez le nombre de machine de fabrication"))
        self.label_lignes.setText(_translate("MainWindow", "Entrez le nombre de lignes de conditionnement"))
        self.label_produit.setText(_translate("MainWindow", "Entrez le nombre des produits "))
import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
MainWindow.setGeometry(300,200,370,250)
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())