# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_prod(object):
    def setupUi(self, Add_prod):
        Add_prod.setObjectName("Add_prod")
        Add_prod.resize(709, 367)
        self.centralwidget = QtWidgets.QWidget(Add_prod)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 30, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(500, 30, 81, 21))
        self.label_3.setObjectName("label_3")
        self.add_product = QtWidgets.QPushButton(self.centralwidget)
        self.add_product.setGeometry(QtCore.QRect(350, 280, 321, 31))
        self.add_product.setObjectName("add_product")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(60, 80, 611, 191))
        self.listView.setObjectName("listView")
        Add_prod.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Add_prod)
        self.statusbar.setObjectName("statusbar")
        Add_prod.setStatusBar(self.statusbar)

        self.retranslateUi(Add_prod)
        QtCore.QMetaObject.connectSlotsByName(Add_prod)

    def retranslateUi(self, Add_prod):
        _translate = QtCore.QCoreApplication.translate
        Add_prod.setWindowTitle(_translate("Add_prod", "MainWindow"))
        self.label.setText(_translate("Add_prod", "3 Machines"))
        self.label_2.setText(_translate("Add_prod", "2 Lignes"))
        self.label_3.setText(_translate("Add_prod", "6 Produits"))
        self.add_product.setText(_translate("Add_prod", "Ajouter un produit"))


import sys
app = QtWidgets.QApplication(sys.argv)
Add_prod = QtWidgets.QMainWindow()
Add_prod.setGeometry(300,200,370,250)
ui = Ui_Add_prod()
ui.setupUi(Add_prod)
Add_prod.show()
sys.exit(app.exec_())